//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebalancedIndustriesRevisited {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebalancedIndustriesRevisited.Localization.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Display both corrected value and original value 的本地化字符串。
        /// </summary>
        public static string BothValue {
            get {
                return ResourceManager.GetString("BothValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting facility multiplier 的本地化字符串。
        /// </summary>
        public static string ExtractingFacilityMultiplier {
            get {
                return ResourceManager.GetString("ExtractingFacilityMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rebalances Industries DLC, reduce traffic flow, increase cargo loading and more. 的本地化字符串。
        /// </summary>
        public static string MOD_Description {
            get {
                return ResourceManager.GetString("MOD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only display corrected value 的本地化字符串。
        /// </summary>
        public static string OriginalValue {
            get {
                return ResourceManager.GetString("OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing facility multiplier 的本地化字符串。
        /// </summary>
        public static string ProcessingFacilityMultiplier {
            get {
                return ResourceManager.GetString("ProcessingFacilityMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Production Rate 的本地化字符串。
        /// </summary>
        public static string ProductionRate {
            get {
                return ResourceManager.GetString("ProductionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This options can be used to regulate the output rate of industrial facilities. Reducing the output rate is good for easing traffic, higher than vanilla will increase productivity but may cause traffic problems. Dynamic adjustment is allowed. 的本地化字符串。
        /// </summary>
        public static string ProductionRateWarning {
            get {
                return ResourceManager.GetString("ProductionRateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tooltip Box Mode 的本地化字符串。
        /// </summary>
        public static string TooltipBoxMode {
            get {
                return ResourceManager.GetString("TooltipBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed incorrect display of vehicle count. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_1_0FIX {
            get {
                return ResourceManager.GetString("UpdateLog_V0_1_0FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Using new algorithms to rebalances Industries. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_1_0UPT1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_1_0UPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Using the latest Harmony API. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_1_0UPT2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_1_0UPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fix some processing buildings appear not enough buyer or not enough raw materials issues. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_2_0FIX {
            get {
                return ResourceManager.GetString("UpdateLog_V0_2_0FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Update buffer recognition and rebinding logic. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_2_0UPT {
            get {
                return ResourceManager.GetString("UpdateLog_V0_2_0UPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed an issue where non-vanilla buildings were not spawns vehicles correctly. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_3_0FIX1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_3_0FIX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed an issue where work space was incorrect. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_3_0FIX2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_3_0FIX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed compatibility issues with IMT and IPT mod. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_3_0FIX3 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_3_0FIX3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed the exception throwing issues. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_3_0FIX4 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_3_0FIX4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed incorrect maintenance costs for unique factories. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_4_0FIX1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_4_0FIX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed issues where hovering over a building pops up tooltipbox with incorrect construction costs, maintenance costs, vehicle counts, and workspace. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_4_0FIX2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_4_0FIX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Added tooltip box mode option, allows display both corrected value and original value. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_5_0ADD {
            get {
                return ResourceManager.GetString("UpdateLog_V0_5_0ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed tooltip box for some buildings still not showing the corrected value. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_5_0FIX1 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_5_0FIX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed worker levelup requirements are too high issues. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_5_0FIX2 {
            get {
                return ResourceManager.GetString("UpdateLog_V0_5_0FIX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ADD]Added Extracting facility and processing facility output rate regulation. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_6_0ADD {
            get {
                return ResourceManager.GetString("UpdateLog_V0_6_0ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed some farm buildings overemployment issues. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_6_0FIX {
            get {
                return ResourceManager.GetString("UpdateLog_V0_6_0FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OPT]Optimized rebinding prefab speed. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_6_0OPT {
            get {
                return ResourceManager.GetString("UpdateLog_V0_6_0OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FIX]Fixed incorrect number of vehicles in the unique factory. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_7_0FIX {
            get {
                return ResourceManager.GetString("UpdateLog_V0_7_0FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [UPT]Updated framework and UI style. 的本地化字符串。
        /// </summary>
        public static string UpdateLog_V0_7_0UPT {
            get {
                return ResourceManager.GetString("UpdateLog_V0_7_0UPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display both corrected value and original value: corrected value (original value), above options need to be set before starting new game or load save. 的本地化字符串。
        /// </summary>
        public static string ValueWarning {
            get {
                return ResourceManager.GetString("ValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vanilla 的本地化字符串。
        /// </summary>
        public static string Vanilla {
            get {
                return ResourceManager.GetString("Vanilla", resourceCulture);
            }
        }
    }
}
