// <auto-generated />
// This file was generated by a T4 template. Do not modify directly.

using CSLModsCommon.Manager;

namespace RebalancedIndustriesRevisited.Localization;

public static class Translations {
    /// <summary>
    /// Production Rate Multiplier
    /// </summary>
    public static string ProductionRateMultiplier => LocalizationManager.Localize("ProductionRateMultiplier");

    /// <summary>
    /// Adjusts the production rate. Higher values make industries produce goods faster, but may also increase traffic congestion. This setting affects all industries (Mod default).
    /// </summary>
    public static string ProductionRateMultiplierDescription => LocalizationManager.Localize("ProductionRateMultiplierDescription");

    /// <summary>
    /// Boat Count
    /// </summary>
    public static string BoatCount => LocalizationManager.Localize("BoatCount");

    /// <summary>
    /// Fishing Harbor
    /// </summary>
    public static string FishingHarbor => LocalizationManager.Localize("FishingHarbor");

    /// <summary>
    /// Reset customized industries settings completed.
    /// </summary>
    public static string ResetCompleted => LocalizationManager.Localize("ResetCompleted");

    /// <summary>
    /// Will reset all customized industries settings to default. This action cannot be undone. Are you sure you want to continue?
    /// </summary>
    public static string SureToResetCustomizedIndustriesSettings => LocalizationManager.Localize("SureToResetCustomizedIndustriesSettings");

    /// <summary>
    /// No customized industries settings.
    /// </summary>
    public static string NoCustomizedIndustriesSettings => LocalizationManager.Localize("NoCustomizedIndustriesSettings");

    /// <summary>
    /// Reset industries customized settings
    /// </summary>
    public static string ResetIndustriesCustomizedSettings => LocalizationManager.Localize("ResetIndustriesCustomizedSettings");

    /// <summary>
    /// Industrial main building
    /// </summary>
    public static string IndustrialMainBuilding => LocalizationManager.Localize("IndustrialMainBuilding");

    /// <summary>
    /// Configuration type
    /// </summary>
    public static string ConfigurationType => LocalizationManager.Localize("ConfigurationType");

    /// <summary>
    /// Custom
    /// </summary>
    public static string Custom => LocalizationManager.Localize("Custom");

    /// <summary>
    /// Mod default
    /// </summary>
    public static string ModDefault => LocalizationManager.Localize("ModDefault");

    /// <summary>
    /// Game default
    /// </summary>
    public static string GameDefault => LocalizationManager.Localize("GameDefault");

    /// <summary>
    /// Highly educated workers
    /// </summary>
    public static string HighlyEducatedWorkers => LocalizationManager.Localize("HighlyEducatedWorkers");

    /// <summary>
    /// Well educated workers
    /// </summary>
    public static string WellEducatedWorkers => LocalizationManager.Localize("WellEducatedWorkers");

    /// <summary>
    /// Educated workers
    /// </summary>
    public static string EducatedWorkers => LocalizationManager.Localize("EducatedWorkers");

    /// <summary>
    /// Uneducated workers
    /// </summary>
    public static string UneducatedWorkers => LocalizationManager.Localize("UneducatedWorkers");

    /// <summary>
    /// Storage capacity
    /// </summary>
    public static string StorageCapacity => LocalizationManager.Localize("StorageCapacity");

    /// <summary>
    /// Output rate
    /// </summary>
    public static string OutputRate => LocalizationManager.Localize("OutputRate");

    /// <summary>
    /// Output truck count
    /// </summary>
    public static string OutputTruckCount => LocalizationManager.Localize("OutputTruckCount");

    /// <summary>
    /// Maintenance cost
    /// </summary>
    public static string MaintenanceCost => LocalizationManager.Localize("MaintenanceCost");

    /// <summary>
    /// Construction cost
    /// </summary>
    public static string ConstructionCost => LocalizationManager.Localize("ConstructionCost");

    /// <summary>
    /// Facility Properties
    /// </summary>
    public static string FacilityProperties => LocalizationManager.Localize("FacilityProperties");

    /// <summary>
    /// Facility name
    /// </summary>
    public static string FacilityName => LocalizationManager.Localize("FacilityName");

    /// <summary>
    /// Facility type
    /// </summary>
    public static string FacilityType => LocalizationManager.Localize("FacilityType");

    /// <summary>
    /// Config
    /// </summary>
    public static string Config => LocalizationManager.Localize("Config");

    /// <summary>
    /// Unique facility
    /// </summary>
    public static string UniqueFacility => LocalizationManager.Localize("UniqueFacility");

    /// <summary>
    /// Warehouse facility
    /// </summary>
    public static string WarehouseFacility => LocalizationManager.Localize("WarehouseFacility");

    /// <summary>
    /// Extracting facility
    /// </summary>
    public static string ExtractingFacility => LocalizationManager.Localize("ExtractingFacility");

    /// <summary>
    /// In order to ensure the normal operation of Rebalanced Industries Revisited Mod, load game function has been disabled, please exit the game and reload save.
    /// </summary>
    public static string LoadGame => LocalizationManager.Localize("LoadGame");

    /// <summary>
    /// Truck Loading Capacity Multiplier Factor
    /// </summary>
    public static string LoadMultiplierFactor => LocalizationManager.Localize("LoadMultiplierFactor");

    /// <summary>
    /// The adjustment of this option will change the load capacity of the vehicle, higher value means that the vehicle can carry more cargo, and the output buffer of the extracting facilities and processing facilities will have a larger capacity to provide more cargo.
    /// </summary>
    public static string LoadMultiplierFactorMinor => LocalizationManager.Localize("LoadMultiplierFactorMinor");

    /// <summary>
    /// Rebalances Industries DLC, reduce traffic flow, increase cargo loading and more.
    /// </summary>
    public static string ModDescription => LocalizationManager.Localize("ModDescription");

    /// <summary>
    /// Open Control Panel
    /// </summary>
    public static string OpenControlPanel => LocalizationManager.Localize("OpenControlPanel");

    /// <summary>
    /// Other functions
    /// </summary>
    public static string OtherFunctionsMajor => LocalizationManager.Localize("OtherFunctionsMajor");

    /// <summary>
    /// Use the shortcut keys or the UUI button to invoke the Control Panel, if you want to adjust the options in the Control Panel, close the Options Panel first
    /// </summary>
    public static string OtherFunctionsMinor => LocalizationManager.Localize("OtherFunctionsMinor");

    /// <summary>
    /// Processing facility
    /// </summary>
    public static string ProcessingFacility => LocalizationManager.Localize("ProcessingFacility");

    /// <summary>
    /// In order to ensure the normal operation of Rebalanced Industries Revisited Mod, back to main menu function has been disabled, please exit the game and reload save.
    /// </summary>
    public static string ToMainMenu => LocalizationManager.Localize("ToMainMenu");

    /// <summary>
    /// This update automatically resets all settings.
    /// </summary>
    public static string Changelog_v1_0_0_Attention => LocalizationManager.Localize("Changelog_v1_0_0_Attention");

    /// <summary>
    /// Added unique factory output rate adjustment options.
    /// </summary>
    public static string Changelog_v1_0_0_Added => LocalizationManager.Localize("Changelog_v1_0_0_Added");

    /// <summary>
    /// Added custom properties for industrial buildings, including construction cost, maintenance cost, truck count, output rate, work place, and storage capacity.
    /// </summary>
    public static string Changelog_v1_0_0_Added1 => LocalizationManager.Localize("Changelog_v1_0_0_Added1");

    /// <summary>
    /// Added mod default values, game default values, custom options to modify industrial building properties.
    /// </summary>
    public static string Changelog_v1_0_0_Added2 => LocalizationManager.Localize("Changelog_v1_0_0_Added2");

}
